spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kdw981129@gmail.com
    password: jfiyimegdukvgqxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://huldduck.clxdd9zh7pfh.ap-northeast-2.rds.amazonaws.com:3306/Idle_DB?useSSL=false
    username: master
    password: rlaehdnr1!


  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_cooments: true

    hibernate:
      ddl-auto: update


  profiles:
    include: jwt


logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hiberante:
        SQL: debug

    boardexample:
      myboard: info
